name: Continuous Integration

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install static analyzers
      if: matrix.os == 'ubuntu-22.04'
      run: >-
        sudo apt-get install clang-tidy-14 cppcheck -y -q

        sudo update-alternatives --install
        /usr/bin/clang-tidy clang-tidy
        /usr/bin/clang-tidy-14 140

    - name: Install build dependencies
      if: matrix.os == 'ubuntu-22.04'
      run: | 
        sudo apt-get update -q
        sudo apt-get install wget libpqxx-dev libopus0 libsodium-dev nlohmann-json3-dev -q -y
        wget -O dpp.deb https://dl.dpp.dev
        wget -O argparse.tar.gz https://github.com/p-ranav/argparse/archive/refs/tags/v2.9.tar.gz
        sudo dpkg -i dpp.deb
        tar -vxf argparse.tar.gz && cd argparse-2.9/ && mkdir build/ && cd build/
        cmake .. && make && sudo make install

    - name: Setup MultiToolTask
      if: matrix.os == 'windows-2022'
      run: |
        Add-Content "$env:GITHUB_ENV" 'UseMultiToolTask=true'
        Add-Content "$env:GITHUB_ENV" 'EnforceProcessCountAcrossBuilds=true'

    - name: Configure
      shell: pwsh
      run: cmake "--preset=ci-$("${{ matrix.os }}".split("-")[0])"

    - name: Build
      run: cmake --build build --config Release -j 2

    - name: Install
      run: cmake --install build --config Release --prefix prefix
